# Generated by Django 3.1.2 on 2020-11-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='total_downloads',
            field=models.IntegerField(null=True),
        ),
    ]
