# Generated by Django 3.1.2 on 2020-11-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_download_total_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='total_downloads',
        ),
    ]
